### ISSUE TITLE
Incorporate linter into the file editor

### ISSUE THREAD

**Issue by ryanhoangt** [All-Hands-AI/openhands-aci#7]
References:
- https://github.com/All-Hands-AI/OpenHands/issues/4636
- https://github.com/All-Hands-AI/OpenHands/pull/4637

**Comment by BradKML** [comment]
Would like to keep on track on this as the logs I got will make the agent get stuck in a loop, and it is pretty persistent at times. https://github.com/All-Hands-AI/OpenHands/issues/4636
